repository:
  has_wiki: false
  has_projects: true
  has_downloads: false
  default_branch: develop 

  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
      enforce_admins: true
      required_linear_history: true
      allow_squash_merge: true
      allow_merge_commit: false
      allow_rebase_merge: false
      required_conversation_resolution: true
      # Add this section to restrict pushes and PRs to main
      restrictions:
        apps: []
        users: []
        teams: []
      # Add this to specify allowed source branches
      required_pull_request_reviews:
        dismissal_restrictions:
          users: []
          teams: []
      required_signatures: false
      lock_branch: false
      allow_fork_syncing: false
      required_deployments: null
      blocks_creations: false
      allow_deletions: false
      allow_force_pushes: false
      required_linear_history: true
      required_conversation_resolution: true
      allows_deletions: false
      allows_force_pushes: false
      description: "Only allow PRs from develop branch"
      pattern: "main"
      rules_configuration:
        - key: base_branch_pattern_matches
          value: "^develop$"
      squash_merge_settings:
        squash_merge_commit_title: "PR_TITLE"
        squash_merge_commit_message: "PR_BODY"
        edit_mode: "DISABLED"

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
      enforce_admins: true
      required_linear_history: true
      allow_squash_merge: true
      allow_merge_commit: false
      allow_rebase_merge: false
      required_conversation_resolution: true
      squash_merge_settings:
        squash_merge_commit_title: "PR_TITLE"
        squash_merge_commit_message: "PR_BODY"
        edit_mode: "DISABLED"

  - name: bugfix/revert-formatting
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
      enforce_admins: true
      required_linear_history: true
      allow_squash_merge: true
      allow_merge_commit: false
      allow_rebase_merge: false
      required_conversation_resolution: true
      squash_merge_settings:
        squash_merge_commit_title: "PR_TITLE"
        squash_merge_commit_message: "PR_BODY"
        edit_mode: "DISABLED"

teams:
  - name: IOS
    permission: push
