repository:
  has_wiki: false
  has_projects: true
  has_downloads: false
  default_branch: develop 

  enable_vulnerability_alerts: true
  enable_automated_security_fixes: true

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
      enforce_admins: true
      required_linear_history: true
      allow_squash_merge: true
      allow_merge_commit: false
      allow_rebase_merge: false

      required_conversation_resolution: true
      squash_merge_settings:
        squash_merge_commit_title: "PR_TITLE"
        squash_merge_commit_message: "PR_BODY"
        edit_mode: "DISABLED"

  - name: develop
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: true
      enforce_admins: true
      required_linear_history: true
      allow_squash_merge: true
      allow_merge_commit: false
      allow_rebase_merge: false
      required_conversation_resolution: true
      squash_merge_settings:
        squash_merge_commit_title: "PR_TITLE"
        squash_merge_commit_message: "PR_BODY"
        edit_mode: "DISABLED"

teams:
  - name: IOS
    permission: push
